// Auto-generated by embed_assets.ps1 鈥?DO NOT EDIT
#ifndef __EMBEDDED_ASSETS_H__
#define __EMBEDDED_ASSETS_H__
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
const uint8_t* embedded_asset_find(const char *filename, uint32_t *out_size);
#ifdef __cplusplus
}
#endif
#endif
