# embed_assets.ps1 — 把 assets/ 下所有 .bin + .pcm 用 objcopy 转成 .o 文件
# 用法: 在项目根目录运行: powershell -File embed_assets.ps1

$ErrorActionPreference = "Stop"
$mingwBin = "T:\C_environment\CksSim\mingw64\bin"
$objcopy  = "$mingwBin\objcopy.exe"
$outDir   = "assets\embedded"

if (-not (Test-Path $objcopy)) {
    Write-Error "objcopy not found: $objcopy"
    exit 1
}

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# 收集所有 .bin 和 .pcm
$files = @()
$files += (Get-ChildItem "assets\pics\*.bin"   | Sort-Object Name)
$files += (Get-ChildItem "assets\audios\*.pcm" | Sort-Object Name)

$entries = @()

foreach ($f in $files) {
    $safeName = ($f.Name -replace '[^a-zA-Z0-9]', '_')
    $oFile   = "$outDir\$($safeName).o"
    $absOFile = "$PSScriptRoot\$oFile"  # 绝对路径

    Write-Host "  objcopy: $($f.Name) -> $oFile"
    Push-Location $f.DirectoryName
    & $objcopy -I binary -O pe-x86-64 -B i386:x86-64 $f.Name $absOFile
    Pop-Location
    if ($LASTEXITCODE -ne 0) { Write-Error "objcopy failed: $($f.Name)"; exit 1 }

    $entries += @{ safe = $safeName; orig = $f.Name; path = $f.FullName.Replace('\','/') }
}

# === 生成 embedded_assets.h ===
$hdr = @'
// Auto-generated by embed_assets.ps1 — DO NOT EDIT
#ifndef __EMBEDDED_ASSETS_H__
#define __EMBEDDED_ASSETS_H__
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
const uint8_t* embedded_asset_find(const char *filename, uint32_t *out_size);
#ifdef __cplusplus
}
#endif
#endif
'@
$hdr | Out-File -FilePath "$outDir\embedded_assets.h" -Encoding UTF8

# === 生成 embedded_assets.c (查找表) ===
$externs = @()
$table   = @()
foreach ($e in $entries) {
    $externs += "extern const uint8_t _binary_$($e.safe)_start[];"
    $externs += "extern const uint8_t _binary_$($e.safe)_end[];"
    $table   += "    { `"$($e.orig)`", _binary_$($e.safe)_start, _binary_$($e.safe)_end },"
}

$cSrc = @"
// Auto-generated by embed_assets.ps1 — DO NOT EDIT
#include "embedded_assets.h"
#include <string.h>
$($externs -join "`n")

typedef struct { const char *name; const uint8_t *start; const uint8_t *end; } emb_t;
static const emb_t emb_list[] = { $($table -join "`n") };
#define EMB_COUNT (sizeof(emb_list)/sizeof(emb_list[0]))

const uint8_t* embedded_asset_find(const char *filepath, uint32_t *out_size) {
    if (!filepath || !out_size) return NULL;
    const char *base = filepath;
    for (const char *p = filepath; *p; p++) { if (*p == '/' || *p == '\\') base = p + 1; }
    for (int i = 0; i < (int)EMB_COUNT; i++) {
        if (strcmp(emb_list[i].name, base) == 0) {
            *out_size = (uint32_t)(emb_list[i].end - emb_list[i].start);
            return emb_list[i].start;
        }
    }
    return NULL;
}
"@
$cSrc | Out-File -FilePath "$outDir\embedded_assets.c" -Encoding UTF8

Write-Host ""
Write-Host "=== Done: $($entries.Count) assets embedded ==="
