// Auto-generated by embed_assets.ps1 鈥?DO NOT EDIT
#include "embedded_assets.h"
#include <string.h>
extern const uint8_t _binary_a_bin_start[];
extern const uint8_t _binary_a_bin_end[];
extern const uint8_t _binary_back_arrow_bin_start[];
extern const uint8_t _binary_back_arrow_bin_end[];
extern const uint8_t _binary_boss_bin_start[];
extern const uint8_t _binary_boss_bin_end[];
extern const uint8_t _binary_bullet_bin_start[];
extern const uint8_t _binary_bullet_bin_end[];
extern const uint8_t _binary_bullet_ember_bin_start[];
extern const uint8_t _binary_bullet_ember_bin_end[];
extern const uint8_t _binary_bullet_stream_bin_start[];
extern const uint8_t _binary_bullet_stream_bin_end[];
extern const uint8_t _binary_bullet_verdant_bin_start[];
extern const uint8_t _binary_bullet_verdant_bin_end[];
extern const uint8_t _binary_CG_img1_bin_start[];
extern const uint8_t _binary_CG_img1_bin_end[];
extern const uint8_t _binary_CG_img2_bin_start[];
extern const uint8_t _binary_CG_img2_bin_end[];
extern const uint8_t _binary_circle_bin_start[];
extern const uint8_t _binary_circle_bin_end[];
extern const uint8_t _binary_coin_bin_start[];
extern const uint8_t _binary_coin_bin_end[];
extern const uint8_t _binary_coin_bar_bin_start[];
extern const uint8_t _binary_coin_bar_bin_end[];
extern const uint8_t _binary_coin_red_bar_bin_start[];
extern const uint8_t _binary_coin_red_bar_bin_end[];
extern const uint8_t _binary_enemy_bin_start[];
extern const uint8_t _binary_enemy_bin_end[];
extern const uint8_t _binary_enemy2_bin_start[];
extern const uint8_t _binary_enemy2_bin_end[];
extern const uint8_t _binary_enemy3_bin_start[];
extern const uint8_t _binary_enemy3_bin_end[];
extern const uint8_t _binary_enemy4_bin_start[];
extern const uint8_t _binary_enemy4_bin_end[];
extern const uint8_t _binary_flame_bin_start[];
extern const uint8_t _binary_flame_bin_end[];
extern const uint8_t _binary_hud_bin_start[];
extern const uint8_t _binary_hud_bin_end[];
extern const uint8_t _binary_hurted_bin_start[];
extern const uint8_t _binary_hurted_bin_end[];
extern const uint8_t _binary_menu_bg_bin_start[];
extern const uint8_t _binary_menu_bg_bin_end[];
extern const uint8_t _binary_play_bg_bin_start[];
extern const uint8_t _binary_play_bg_bin_end[];
extern const uint8_t _binary_play_hud_bin_start[];
extern const uint8_t _binary_play_hud_bin_end[];
extern const uint8_t _binary_player_bin_start[];
extern const uint8_t _binary_player_bin_end[];
extern const uint8_t _binary_player_ember_bin_start[];
extern const uint8_t _binary_player_ember_bin_end[];
extern const uint8_t _binary_player_stream_bin_start[];
extern const uint8_t _binary_player_stream_bin_end[];
extern const uint8_t _binary_player_verdant_bin_start[];
extern const uint8_t _binary_player_verdant_bin_end[];
extern const uint8_t _binary_setting_icon_bin_start[];
extern const uint8_t _binary_setting_icon_bin_end[];
extern const uint8_t _binary_shop_bg_bin_start[];
extern const uint8_t _binary_shop_bg_bin_end[];
extern const uint8_t _binary_triangle_bin_start[];
extern const uint8_t _binary_triangle_bin_end[];
extern const uint8_t _binary_basketballmusic_pcm_start[];
extern const uint8_t _binary_basketballmusic_pcm_end[];
extern const uint8_t _binary_bgm_pcm_start[];
extern const uint8_t _binary_bgm_pcm_end[];
extern const uint8_t _binary_cg_pcm_start[];
extern const uint8_t _binary_cg_pcm_end[];
extern const uint8_t _binary_johnnybacon156fah_pcm_start[];
extern const uint8_t _binary_johnnybacon156fah_pcm_end[];
extern const uint8_t _binary_jonasblakewoodtropical_pcm_start[];
extern const uint8_t _binary_jonasblakewoodtropical_pcm_end[];
extern const uint8_t _binary_PixelGameShopMusic_pcm_start[];
extern const uint8_t _binary_PixelGameShopMusic_pcm_end[];
extern const uint8_t _binary_SoftBaseAmbient_pcm_start[];
extern const uint8_t _binary_SoftBaseAmbient_pcm_end[];

typedef struct { const char *name; const uint8_t *start; const uint8_t *end; } emb_t;
static const emb_t emb_list[] = {     { "a.bin", _binary_a_bin_start, _binary_a_bin_end },
    { "back_arrow.bin", _binary_back_arrow_bin_start, _binary_back_arrow_bin_end },
    { "boss.bin", _binary_boss_bin_start, _binary_boss_bin_end },
    { "bullet.bin", _binary_bullet_bin_start, _binary_bullet_bin_end },
    { "bullet_ember.bin", _binary_bullet_ember_bin_start, _binary_bullet_ember_bin_end },
    { "bullet_stream.bin", _binary_bullet_stream_bin_start, _binary_bullet_stream_bin_end },
    { "bullet_verdant.bin", _binary_bullet_verdant_bin_start, _binary_bullet_verdant_bin_end },
    { "CG_img1.bin", _binary_CG_img1_bin_start, _binary_CG_img1_bin_end },
    { "CG_img2.bin", _binary_CG_img2_bin_start, _binary_CG_img2_bin_end },
    { "circle.bin", _binary_circle_bin_start, _binary_circle_bin_end },
    { "coin.bin", _binary_coin_bin_start, _binary_coin_bin_end },
    { "coin_bar.bin", _binary_coin_bar_bin_start, _binary_coin_bar_bin_end },
    { "coin_red_bar.bin", _binary_coin_red_bar_bin_start, _binary_coin_red_bar_bin_end },
    { "enemy.bin", _binary_enemy_bin_start, _binary_enemy_bin_end },
    { "enemy2.bin", _binary_enemy2_bin_start, _binary_enemy2_bin_end },
    { "enemy3.bin", _binary_enemy3_bin_start, _binary_enemy3_bin_end },
    { "enemy4.bin", _binary_enemy4_bin_start, _binary_enemy4_bin_end },
    { "flame.bin", _binary_flame_bin_start, _binary_flame_bin_end },
    { "hud.bin", _binary_hud_bin_start, _binary_hud_bin_end },
    { "hurted.bin", _binary_hurted_bin_start, _binary_hurted_bin_end },
    { "menu_bg.bin", _binary_menu_bg_bin_start, _binary_menu_bg_bin_end },
    { "play_bg.bin", _binary_play_bg_bin_start, _binary_play_bg_bin_end },
    { "play_hud.bin", _binary_play_hud_bin_start, _binary_play_hud_bin_end },
    { "player.bin", _binary_player_bin_start, _binary_player_bin_end },
    { "player_ember.bin", _binary_player_ember_bin_start, _binary_player_ember_bin_end },
    { "player_stream.bin", _binary_player_stream_bin_start, _binary_player_stream_bin_end },
    { "player_verdant.bin", _binary_player_verdant_bin_start, _binary_player_verdant_bin_end },
    { "setting_icon.bin", _binary_setting_icon_bin_start, _binary_setting_icon_bin_end },
    { "shop_bg.bin", _binary_shop_bg_bin_start, _binary_shop_bg_bin_end },
    { "triangle.bin", _binary_triangle_bin_start, _binary_triangle_bin_end },
    { "basketballmusic.pcm", _binary_basketballmusic_pcm_start, _binary_basketballmusic_pcm_end },
    { "bgm.pcm", _binary_bgm_pcm_start, _binary_bgm_pcm_end },
    { "cg.pcm", _binary_cg_pcm_start, _binary_cg_pcm_end },
    { "johnnybacon156fah.pcm", _binary_johnnybacon156fah_pcm_start, _binary_johnnybacon156fah_pcm_end },
    { "jonasblakewoodtropical.pcm", _binary_jonasblakewoodtropical_pcm_start, _binary_jonasblakewoodtropical_pcm_end },
    { "PixelGameShopMusic.pcm", _binary_PixelGameShopMusic_pcm_start, _binary_PixelGameShopMusic_pcm_end },
    { "SoftBaseAmbient.pcm", _binary_SoftBaseAmbient_pcm_start, _binary_SoftBaseAmbient_pcm_end }, };
#define EMB_COUNT (sizeof(emb_list)/sizeof(emb_list[0]))

const uint8_t* embedded_asset_find(const char *filepath, uint32_t *out_size) {
    if (!filepath || !out_size) return NULL;
    const char *base = filepath;
    for (const char *p = filepath; *p; p++) { if (*p == '/' || *p == '\\') base = p + 1; }
    for (int i = 0; i < (int)EMB_COUNT; i++) {
        if (strcmp(emb_list[i].name, base) == 0) {
            *out_size = (uint32_t)(emb_list[i].end - emb_list[i].start);
            return emb_list[i].start;
        }
    }
    return NULL;
}
